add optional field: ResourceRequest in the swagger
neuqlz/azure-rest-api-specs pull request #1
Opened 2021-03-05 03:57 UTC by neuqlz

2021-03-08 02:47 UTC, allxiao commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required CPU, basic tier should be 1, standard tier should be in range (1, 4), it will be deprecated since api version 2020-11-01-preview, please leverage the ResourceReques
Not specifically for this PR.

* I think we should use `[1, 4]` here. 
* `,` should be replaced with `.`
* Inconsistent case: `api` -> `API`, `cpu` -> `CPU`.
* Some grammar error.

Maybe:
```
Required CPU. This should be 1 for Basic tier, and in range [1, 4] for Standard tier. This is deprecated starting from API version 2020-11-01-preview. Please use the ResourceRequest field to set the CPU size.
```

2021-03-08 02:48 UTC, allxiao commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "The request of quantity for cpu and memory size."
The requested CPU and memory quantity.

2021-03-08 02:48 UTC, allxiao commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required CPU, basic tier should be 1, standard tier should be in range (1, 4), it will be deprecated since api version 2020-11-01-preview, please leverage the ResourceReques
Same for below.

2021-03-08 02:51 UTC, allxiao commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required CPU, 1c can be represent by 1 or 1000m, basic tier should be 500m or 1, standard tier should be 500m or the value in range (1, 4).",
Maybe:

```
Required CPU. 1 core can be represented by 1 or 1000m. This should be 500m or 1 for Basic tier, and {500m, 1, 2, 3, 4} for Standard tier.
```

2021-03-08 02:53 UTC, allxiao commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required Memory size, 1GB can be represent by 1Gi or 1024Mi, basic tier should be 500m or the value in range (1, 2), standard tier should be 500m or the value in range (1, 8
Maybe

```
Required memory. 1 GB can be represented by 1Gi or 1024Mi. This should be {500m, 1Gi, 2Gi} for Basic tier, and {500m, 1Gi, 2Gi, ..., 8Gi} for Standard tier.
```

2021-03-08 02:57 UTC, allxiao requested changes
We need to update the descriptions.

2021-03-08 03:33 UTC, neuqlz commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "The request of quantity for cpu and memory size."
fixed

2021-03-08 03:34 UTC, neuqlz commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required CPU, 1c can be represent by 1 or 1000m, basic tier should be 500m or 1, standard tier should be 500m or the value in range (1, 4).",
fixed

2021-03-08 03:34 UTC, neuqlz commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required Memory size, 1GB can be represent by 1Gi or 1024Mi, basic tier should be 500m or the value in range (1, 2), standard tier should be 500m or the value in range (1, 8
fixed

2021-03-08 03:34 UTC, neuqlz commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +          "description": "Required CPU, basic tier should be 1, standard tier should be in range (1, 4), it will be deprecated since api version 2020-11-01-preview, please leverage the ResourceReques
fixed

2021-03-08 06:01 UTC, neuqlz commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2020-11-01-preview/appplatform.json
> +    "ResourceRequest": {
yep, fixed.

2021-03-09 05:32 UTC, allxiao commented
lgtm

2021-03-09 06:30 UTC, merged